apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: flyt-isy-graving-gateway_ofk_no
      fintlabs.no/org-id: ofk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ofk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/ofk-no/api/isygraving/instances"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/beta/ofk-no/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/ofk-no/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/beta/ofk-no/actuator/health/liveness"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "ofk-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: server.servlet.context-path
          value: "/beta/ofk-no"
    target:
      kind: Application
      name: flyt-isy-graving-gateway
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/novari-flyt-isy-graving-gateway-out"
    target:
      kind: OnePasswordItem
      name: novari-flyt-isy-graving-dispatch-oauth2-client
