apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: flyt-isy-graving-gateway_vestfoldfylke_no
      fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vestfoldfylke-no/api/isygraving/instances"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "vestfoldfylke-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: server.servlet.context-path
          value: "/beta/vestfoldfylke-no"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/beta/vestfoldfylke-no/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/vestfoldfylke-no/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/beta/vestfoldfylke-no/actuator/health/liveness"

    target:
      kind: Application
      name: flyt-isy-graving-gateway
