fint:
  application-id: fint-flyt-isy-graving-gateway

novari:
  flyt:
    isy-graving:
      dispatch:
        enabled: true

logging:
  level:
    no.novari.cache.ehcache.FintEhCacheEventLogger: WARN
    no.novari.flyt.webresourceserver: DEBUG

server:
  error:
    include-message: always
  max-http-request-header-size: 40KB

spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-postgres
      - flyt-web-resource-server
      - flyt-file-web-client
      - flyt-dispatch-web-client

  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    path: ${novari.flyt.isy-graving.swagger.base-path:${novari.flyt.isy-graving.api.base-path:/api/isygraving/instances}}/swagger-ui
  api-docs:
    path: ${novari.flyt.isy-graving.swagger.base-path:${novari.flyt.isy-graving.api.base-path:/api/isygraving/instances}}/v3/api-docs
