fint:
  org-id: novari.no
novari:
  flyt:
    isy-graving:
      dispatch:
        enabled: false
    file-service-url: http://localhost:8091
    web-instance-gateway:
      check-integration-exists: false
  kafka:
    default-replicas: 1
    topic:
      org-id: novari-no
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5442/flyt-isy-graving-gateway
    username: postgres
    password: password
    hikari:
      schema: fintlabs_no
server:
  port: 8107
