apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: flyt-isygraving-gateway_afk_no
      fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "/afk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/afk-no/api/isygraving"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "afk-no"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/actuator/health"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/actuator/prometheus"
    target:
      kind: Application
      name: flyt-isygraving-gateway
