apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-isy-graving-gateway_afk_no
      fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/afk-no/api/isygraving/instances"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/beta/afk-no/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/afk-no/actuator/health/readiness"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/beta/afk-no/actuator/health/liveness"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "afk-no"
      - op: add
        path: "/spec/env/-"
        value:
          name: server.servlet.context-path
          value: "/beta/afk-no"
    target:
      kind: Application
      name: fint-flyt-isy-graving-gateway
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: logging.level.no.novari.flyt.isygraving.gateway.dispatch
          value: "DEBUG"
    target:
      kind: Application
      name: fint-flyt-isy-graving-gateway
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/novari-fint-flyt-isy-graving-gateway-out"
    target:
      kind: OnePasswordItem
      name: novari-flyt-isy-graving-dispatch-oauth2-client
