apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: flyt-isygraving-gateway_bfk_no
      fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "/beta/bfk.no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/bfk-no/api/isygraving"
      - op: add
        path: "/spec/env/-"
        value:
          name: novari.kafka.topic.org-id
          value: "bfk-no"
      - op: replace
        path: "/spec/probes/startup/path"
        value: "/beta/bfk-no/actuator/health"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/bfk-no/actuator/health"
      - op: replace
        path: "/spec/probes/liveness/path"
        value: "/beta/bfk-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/bfk-no/actuator/prometheus"
    target:
      kind: Application
      name: flyt-isygraving-gateway
